# Generated by Django 5.1.6 on 2025-05-09 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_student_address_student_course_student_gender_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Information Technology', 'Information Technology'), ('Fine Arts', 'Fine Arts'), ('Literature', 'Literature'), ('Engineering', 'Engineering'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Music', 'Music'), ('Physical Education', 'Physical Education')], default='Computer Science', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')], default=3),
        ),
        migrations.AlterField(
            model_name='student',
            name='interest',
            field=models.CharField(choices=[('Arts', 'Arts'), ('Science', 'Science'), ('Technology', 'Technology'), ('Engineering', 'Engineering'), ('Mathematics', 'Mathematics'), ('Literature', 'Literature'), ('Music', 'Music'), ('Sports', 'Sports')], default='Arts', max_length=100),
        ),
    ]
