# Generated by Django 5.1.6 on 2025-05-09 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0003_remove_student_date_of_birth_alter_student_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('BSCS', 'Bachelor of Science in Computer Science'), ('BSIT', 'Bachelor of Science in Information Technology'), ('BFA', 'Bachelor of Fine Arts'), ('BA-LIT', 'Bachelor of Arts in Literature'), ('BSEE', 'Bachelor of Science in Electrical Engineering'), ('BSME', 'Bachelor of Science in Mechanical Engineering'), ('BSMath', 'Bachelor of Science in Mathematics'), ('BSPhysics', 'Bachelor of Science in Physics'), ('BMus', 'Bachelor of Music'), ('BSPE', 'Bachelor of Science in Physical Education'), ('BSIS', 'Bachelor of Science in Information Systems'), ('BSData', 'Bachelor of Science in Data Science'), ('BDes', 'Bachelor of Design'), ('BBA', 'Bachelor of Business Administration'), ('BSPsych', 'Bachelor of Science in Psychology'), ('BSMed', 'Bachelor of Science in Medical Sciences'), ('BA-Lang', 'Bachelor of Arts in Foreign Languages'), ('BBA-DM', 'Bachelor of Business Administration in Digital Marketing'), ('BA-Anim', 'Bachelor of Arts in Animation'), ('BA-Photo', 'Bachelor of Arts in Photography'), ('BSRobo', 'Bachelor of Science in Robotics Engineering'), ('BSAI', 'Bachelor of Science in Artificial Intelligence'), ('BSGame', 'Bachelor of Science in Game Development'), ('BArch', 'Bachelor of Architecture'), ('BSFash', 'Bachelor of Science in Fashion Technology'), ('BSEnv', 'Bachelor of Science in Environmental Science'), ('BA-Comm', 'Bachelor of Arts in Mass Communication'), ('BA-Film', 'Bachelor of Arts in Film Production'), ('BS-Cul', 'Bachelor of Science in Culinary Arts Management')], default='BSCS', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='interest',
            field=models.CharField(choices=[('Arts', 'Arts'), ('Science', 'Science'), ('Technology', 'Technology'), ('Engineering', 'Engineering'), ('Mathematics', 'Mathematics'), ('Literature', 'Literature'), ('Music', 'Music'), ('Sports', 'Sports'), ('Coding', 'Coding'), ('Web Development', 'Web Development'), ('Data Science', 'Data Science'), ('Design', 'Design'), ('Business', 'Business'), ('Languages', 'Languages'), ('Medicine', 'Medicine'), ('Psychology', 'Psychology'), ('Digital Marketing', 'Digital Marketing'), ('Animation', 'Animation'), ('Photography', 'Photography'), ('Robotics', 'Robotics'), ('Artificial Intelligence', 'Artificial Intelligence'), ('Game Development', 'Game Development'), ('Architecture', 'Architecture'), ('Fashion Design', 'Fashion Design'), ('Environmental Science', 'Environmental Science'), ('Journalism', 'Journalism'), ('Film Making', 'Film Making'), ('Culinary Arts', 'Culinary Arts')], default='Arts', max_length=100),
        ),
    ]
