# Generated by Django 5.1.6 on 2025-05-09 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_alter_student_course_alter_student_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='interest',
            field=models.TextField(blank=True),
        ),
    ]
